version: '3.3'
# docker-compose --compatibility up
services:
  ship_crawler:
    build:
      context: ./image
      dockerfile: dockerfile
    image: iii/ship_crawler-python3.8.3:v1.0
    container_name: ship_crawler
    deploy:
      resources:
        limits:
          cpus: '1.000'
          memory: 1G
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
    environment:
      TZ: "Asia/Taipei"
      LANG: C.UTF-8
      API_PROPERTY : "FORMALITY"
    volumes:
      - ./src:/app