if __name__ == '__main__':
    import sys
    sys.path.append('/app/')
from uuid import uuid1
from sqlalchemy           import Column, String, DateTime, text, Text
from settings.environment import db

class MMSI_Info(db.Model):
    __tablename__ = 'mmsi_info'
    id            = Column('id',      String(36), primary_key=True)
    mmsi          = Column('mmsi',    String(3),  nullable=False)
    country       = Column('country', Text, nullable=False)
    alpha_2       = Column('alpha_2', String(2), nullable=False)
    alpha_3       = Column('alpha_3', String(3))
    created_time  = Column('created_time', DateTime, server_default=text('CURRENT_TIMESTAMP'))
    updated_time  = Column('updated_time', DateTime, server_default=text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    def __init__(self, mmsi, country, alpha_2, alpha_3=None, *args, **kwargs):
        self.id      = '{}'.format(uuid1())
        self.mmsi    = mmsi
        self.alpha_2 = alpha_2
        self.alpha_3 = alpha_3
        self.country = country
# db.create_all()

# mmsi_dict = {
#     '201': {'alpha_2': 'AL', 'alpha_3': 'ALB', 'country': 'Albania'},
#     '202': {'alpha_2': 'AD', 'alpha_3': 'AND', 'country': 'Andorra'},
#     '203': {'alpha_2': 'AT', 'alpha_3': 'AUT', 'country': 'Austria'},
#     '204': {'alpha_2': 'PT', 'alpha_3': 'PRT', 'country': 'Portugal'},
#     '205': {'alpha_2': 'BE', 'alpha_3': 'BEL', 'country': 'Belgium'},
#     '206': {'alpha_2': 'BY', 'alpha_3': 'BLR', 'country': 'Belarus'},
#     '207': {'alpha_2': 'BG', 'alpha_3': 'BGR', 'country': 'Bulgaria'},
#     '208': {'alpha_2': 'VA', 'alpha_3': 'VAT', 'country': 'Vatican'},
#     '209': {'alpha_2': 'CY', 'alpha_3': 'CYP', 'country': 'Cyprus'},
#     '210': {'alpha_2': 'CY', 'alpha_3': 'CYP', 'country': 'Cyprus'},
#     '211': {'alpha_2': 'DE', 'alpha_3': 'DEU', 'country': 'Germany'},
#     '212': {'alpha_2': 'CY', 'alpha_3': 'CYP', 'country': 'Cyprus'},
#     '213': {'alpha_2': 'GE', 'alpha_3': 'GEO', 'country': 'Georgia'},
#     '214': {'alpha_2': 'MD', 'alpha_3': 'MDA', 'country': 'Moldova'},
#     '215': {'alpha_2': 'MT', 'alpha_3': 'MLT', 'country': 'Malta'},
#     '216': {'alpha_2': 'ZZ', 'alpha_3': None, 'country': 'Armenia'},
#     '218': {'alpha_2': 'DE', 'alpha_3': 'DEU', 'country': 'Germany'},
#     '219': {'alpha_2': 'DK', 'alpha_3': 'DNK', 'country': 'Denmark'},
#     '220': {'alpha_2': 'DK', 'alpha_3': 'DNK', 'country': 'Denmark'},
#     '224': {'alpha_2': 'ES', 'alpha_3': 'ESP', 'country': 'Spain'},
#     '225': {'alpha_2': 'ES', 'alpha_3': 'ESP', 'country': 'Spain'},
#     '226': {'alpha_2': 'FR', 'alpha_3': 'FRA', 'country': 'France'},
#     '227': {'alpha_2': 'FR', 'alpha_3': 'FRA', 'country': 'France'},
#     '228': {'alpha_2': 'FR', 'alpha_3': 'FRA', 'country': 'France'},
#     '229': {'alpha_2': 'MT', 'alpha_3': 'MLT', 'country': 'Malta'},
#     '230': {'alpha_2': 'FI', 'alpha_3': 'FIN', 'country': 'Finland'},
#     '231': {'alpha_2': 'FO', 'alpha_3': 'FRO', 'country': 'Faroe Is'},
#     '232': {'alpha_2': 'GB', 'alpha_3': 'GBR', 'country': 'United Kingdom'},
#     '233': {'alpha_2': 'GB', 'alpha_3': 'GBR', 'country': 'United Kingdom'},
#     '234': {'alpha_2': 'GB', 'alpha_3': 'GBR', 'country': 'United Kingdom'},
#     '235': {'alpha_2': 'GB', 'alpha_3': 'GBR', 'country': 'United Kingdom'},
#     '236': {'alpha_2': 'GI', 'alpha_3': 'GIB', 'country': 'Gibraltar'},
#     '237': {'alpha_2': 'GR', 'alpha_3': 'GRC', 'country': 'Greece'},
#     '238': {'alpha_2': 'HR', 'alpha_3': 'HRV', 'country': 'Croatia'},
#     '239': {'alpha_2': 'GR', 'alpha_3': 'GRC', 'country': 'Greece'},
#     '240': {'alpha_2': 'GR', 'alpha_3': 'GRC', 'country': 'Greece'},
#     '241': {'alpha_2': 'GR', 'alpha_3': 'GRC', 'country': 'Greece'},
#     '242': {'alpha_2': 'MA', 'alpha_3': 'MAR', 'country': 'Morocco'},
#     '243': {'alpha_2': 'HU', 'alpha_3': 'HUN', 'country': 'Hungary'},
#     '244': {'alpha_2': 'NL', 'alpha_3': 'NLD', 'country': 'Netherlands'},
#     '245': {'alpha_2': 'NL', 'alpha_3': 'NLD', 'country': 'Netherlands'},
#     '246': {'alpha_2': 'NL', 'alpha_3': 'NLD', 'country': 'Netherlands'},
#     '247': {'alpha_2': 'IT', 'alpha_3': 'ITA', 'country': 'Italy'},
#     '248': {'alpha_2': 'MT', 'alpha_3': 'MLT', 'country': 'Malta'},
#     '249': {'alpha_2': 'MT', 'alpha_3': 'MLT', 'country': 'Malta'},
#     '250': {'alpha_2': 'IE', 'alpha_3': 'IRL', 'country': 'Ireland'},
#     '251': {'alpha_2': 'IS', 'alpha_3': 'ISL', 'country': 'Iceland'},
#     '252': {'alpha_2': 'LI', 'alpha_3': 'LIE', 'country': 'Liechtenstein'},
#     '253': {'alpha_2': 'LU', 'alpha_3': 'LUX', 'country': 'Luxembourg'},
#     '254': {'alpha_2': 'MC', 'alpha_3': 'MCO', 'country': 'Monaco'},
#     '255': {'alpha_2': 'PT', 'alpha_3': 'PRT', 'country': 'Portugal'},
#     '256': {'alpha_2': 'MT', 'alpha_3': 'MLT', 'country': 'Malta'},
#     '257': {'alpha_2': 'NO', 'alpha_3': 'NOR', 'country': 'Norway'},
#     '258': {'alpha_2': 'NO', 'alpha_3': 'NOR', 'country': 'Norway'},
#     '259': {'alpha_2': 'NO', 'alpha_3': 'NOR', 'country': 'Norway'},
#     '261': {'alpha_2': 'PL', 'alpha_3': 'POL', 'country': 'Poland'},
#     '262': {'alpha_2': 'ME', 'alpha_3': 'MNE', 'country': 'Montenegro'},
#     '263': {'alpha_2': 'PT', 'alpha_3': 'PRT', 'country': 'Portugal'},
#     '264': {'alpha_2': 'RO', 'alpha_3': 'ROU', 'country': 'Romania'},
#     '265': {'alpha_2': 'SE', 'alpha_3': 'SWE', 'country': 'Sweden'},
#     '266': {'alpha_2': 'SE', 'alpha_3': 'SWE', 'country': 'Sweden'},
#     '267': {'alpha_2': 'SK', 'alpha_3': 'SVK', 'country': 'Slovakia'},
#     '268': {'alpha_2': 'SM', 'alpha_3': 'SMR', 'country': 'San Marino'},
#     '269': {'alpha_2': 'CH', 'alpha_3': 'CHE', 'country': 'Switzerland'},
#     '270': {'alpha_2': 'CZ', 'alpha_3': 'CZE', 'country': 'Czech Republic'},
#     '271': {'alpha_2': 'TR', 'alpha_3': 'TUR', 'country': 'Turkey'},
#     '272': {'alpha_2': 'UA', 'alpha_3': 'UKR', 'country': 'Ukraine'},
#     '273': {'alpha_2': 'RU', 'alpha_3': 'RUS', 'country': 'Russia'},
#     '274': {'alpha_2': 'MK', 'alpha_3': 'MKD', 'country': 'FYR Macedonia'},
#     '275': {'alpha_2': 'LV', 'alpha_3': 'LVA', 'country': 'Latvia'},
#     '276': {'alpha_2': 'EE', 'alpha_3': 'EST', 'country': 'Estonia'},
#     '277': {'alpha_2': 'LT', 'alpha_3': 'LTU', 'country': 'Lithuania'},
#     '278': {'alpha_2': 'SI', 'alpha_3': 'SVN', 'country': 'Slovenia'},
#     '279': {'alpha_2': 'RS', 'alpha_3': 'SRB', 'country': 'Serbia'},
#     '301': {'alpha_2': 'AI', 'alpha_3': 'AIA', 'country': 'Anguilla'},
#     '303': {'alpha_2': 'US', 'alpha_3': 'USA', 'country': 'USA'},
#     '304': {'alpha_2': 'AG', 'alpha_3': 'ATG', 'country': 'Antigua Barbuda'},
#     '305': {'alpha_2': 'AG', 'alpha_3': 'ATG', 'country': 'Antigua Barbuda'},
#     '306': {'alpha_2': 'CW', 'alpha_3': 'CUW', 'country': 'Curacao'},
#     '307': {'alpha_2': 'AW', 'alpha_3': 'ABW', 'country': 'Aruba'},
#     '308': {'alpha_2': 'BS', 'alpha_3': 'BHS', 'country': 'Bahamas'},
#     '309': {'alpha_2': 'BS', 'alpha_3': 'BHS', 'country': 'Bahamas'},
#     '310': {'alpha_2': 'BM', 'alpha_3': 'BMU', 'country': 'Bermuda'},
#     '311': {'alpha_2': 'BS', 'alpha_3': 'BHS', 'country': 'Bahamas'},
#     '312': {'alpha_2': 'BZ', 'alpha_3': 'BLZ', 'country': 'Belize'},
#     '314': {'alpha_2': 'BB', 'alpha_3': 'BRB', 'country': 'Barbados'},
#     '316': {'alpha_2': 'CA', 'alpha_3': 'CAN', 'country': 'Canada'},
#     '319': {'alpha_2': 'KY', 'alpha_3': 'CYM', 'country': 'Cayman Is'},
#     '321': {'alpha_2': 'CR', 'alpha_3': 'CRI', 'country': 'Costa Rica'},
#     '323': {'alpha_2': 'CU', 'alpha_3': 'CUB', 'country': 'Cuba'},
#     '325': {'alpha_2': 'DM', 'alpha_3': 'DMA', 'country': 'Dominica'},
#     '327': {'alpha_2': 'DO', 'alpha_3': 'DOM', 'country': 'Dominican Rep'},
#     '329': {'alpha_2': 'GP', 'alpha_3': 'GLP', 'country': 'Guadeloupe'},
#     '330': {'alpha_2': 'GD', 'alpha_3': 'GRD', 'country': 'Grenada'},
#     '331': {'alpha_2': 'GL', 'alpha_3': 'GRL', 'country': 'Greenland'},
#     '332': {'alpha_2': 'GT', 'alpha_3': 'GTM', 'country': 'Guatemala'},
#     '334': {'alpha_2': 'HN', 'alpha_3': 'HND', 'country': 'Honduras'},
#     '336': {'alpha_2': 'HT', 'alpha_3': 'HTI', 'country': 'Haiti'},
#     '338': {'alpha_2': 'US', 'alpha_3': 'USA', 'country': 'USA'},
#     '339': {'alpha_2': 'JM', 'alpha_3': 'JAM', 'country': 'Jamaica'},
#     '341': {'alpha_2': 'KN', 'alpha_3': 'KNA', 'country': 'St Kitts Nevis'},
#     '343': {'alpha_2': 'LC', 'alpha_3': 'LCA', 'country': 'St Lucia'},
#     '345': {'alpha_2': 'MX', 'alpha_3': 'MEX', 'country': 'Mexico'},
#     '347': {'alpha_2': 'MQ', 'alpha_3': 'MTQ', 'country': 'Martinique'},
#     '348': {'alpha_2': 'MS', 'alpha_3': 'MSR', 'country': 'Montserrat'},
#     '350': {'alpha_2': 'NI', 'alpha_3': 'NIC', 'country': 'Nicaragua'},
#     '351': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '352': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '353': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '354': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '355': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '356': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '357': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '358': {'alpha_2': 'PR', 'alpha_3': 'PRI', 'country': 'Puerto Rico'},
#     '359': {'alpha_2': 'SV', 'alpha_3': 'SLV', 'country': 'El Salvador'},
#     '361': {'alpha_2': 'PM', 'alpha_3': 'SPM', 'country': 'St Pierre Miquelon'},
#     '362': {'alpha_2': 'TT', 'alpha_3': 'TTO', 'country': 'Trinidad Tobago'},
#     '364': {'alpha_2': 'TC', 'alpha_3': 'TCA', 'country': 'Turks Caicos Is'},
#     '366': {'alpha_2': 'US', 'alpha_3': 'USA', 'country': 'USA'},
#     '367': {'alpha_2': 'US', 'alpha_3': 'USA', 'country': 'USA'},
#     '368': {'alpha_2': 'US', 'alpha_3': 'USA', 'country': 'USA'},
#     '369': {'alpha_2': 'US', 'alpha_3': 'USA', 'country': 'USA'},
#     '370': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '371': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '372': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '373': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '374': {'alpha_2': 'PA', 'alpha_3': 'PAN', 'country': 'Panama'},
#     '375': {'alpha_2': 'VC', 'alpha_3': 'VCT', 'country': 'St Vincent Grenadines'},
#     '376': {'alpha_2': 'VC', 'alpha_3': 'VCT', 'country': 'St Vincent Grenadines'},
#     '377': {'alpha_2': 'VC', 'alpha_3': 'VCT', 'country': 'St Vincent Grenadines'},
#     '378': {'alpha_2': 'VG', 'alpha_3': 'VGB', 'country': 'British Virgin Is'},
#     '379': {'alpha_2': 'VI', 'alpha_3': 'VIR', 'country': 'US Virgin Is'},
#     '401': {'alpha_2': 'AF', 'alpha_3': 'AFG', 'country': 'Afghanistan'},
#     '403': {'alpha_2': 'SA', 'alpha_3': 'SAU', 'country': 'Saudi Arabia'},
#     '405': {'alpha_2': 'BD', 'alpha_3': 'BGD', 'country': 'Bangladesh'},
#     '408': {'alpha_2': 'BH', 'alpha_3': 'BHR', 'country': 'Bahrain'},
#     '410': {'alpha_2': 'BT', 'alpha_3': 'BTN', 'country': 'Bhutan'},
#     '412': {'alpha_2': 'CN', 'alpha_3': 'CHN', 'country': 'China'},
#     '413': {'alpha_2': 'CN', 'alpha_3': 'CHN', 'country': 'China'},
#     '414': {'alpha_2': 'CN', 'alpha_3': 'CHN', 'country': 'China'},
#     '416': {'alpha_2': 'TW', 'alpha_3': 'TWN', 'country': 'Taiwan'},
#     '417': {'alpha_2': 'LK', 'alpha_3': 'LKA', 'country': 'Sri Lanka'},
#     '419': {'alpha_2': 'IN', 'alpha_3': 'IND', 'country': 'India'},
#     '422': {'alpha_2': 'IR', 'alpha_3': 'IRN', 'country': 'Iran'},
#     '423': {'alpha_2': 'AZ', 'alpha_3': 'AZE', 'country': 'Azerbaijan'},
#     '425': {'alpha_2': 'IQ', 'alpha_3': 'IRQ', 'country': 'Iraq'},
#     '428': {'alpha_2': 'IL', 'alpha_3': 'ISR', 'country': 'Israel'},
#     '431': {'alpha_2': 'JP', 'alpha_3': 'JPN', 'country': 'Japan'},
#     '432': {'alpha_2': 'JP', 'alpha_3': 'JPN', 'country': 'Japan'},
#     '434': {'alpha_2': 'TM', 'alpha_3': 'TKM', 'country': 'Turkmenistan'},
#     '436': {'alpha_2': 'KZ', 'alpha_3': 'KAZ', 'country': 'Kazakhstan'},
#     '437': {'alpha_2': 'UZ', 'alpha_3': 'UZB', 'country': 'Uzbekistan'},
#     '438': {'alpha_2': 'JO', 'alpha_3': 'JOR', 'country': 'Jordan'},
#     '440': {'alpha_2': 'KR', 'alpha_3': 'KOR', 'country': 'Korea'},
#     '441': {'alpha_2': 'KR', 'alpha_3': 'KOR', 'country': 'Korea'},
#     '443': {'alpha_2': 'PS', 'alpha_3': 'PSE', 'country': 'Palestine'},
#     '445': {'alpha_2': 'KP', 'alpha_3': 'PRK', 'country': 'DPR Korea'},
#     '447': {'alpha_2': 'KW', 'alpha_3': 'KWT', 'country': 'Kuwait'},
#     '450': {'alpha_2': 'LB', 'alpha_3': 'LBN', 'country': 'Lebanon'},
#     '451': {'alpha_2': 'ZZ', 'alpha_3': None, 'country': 'Kyrgyz Republic'},
#     '453': {'alpha_2': 'ZZ', 'alpha_3': None, 'country': 'Macao'},
#     '455': {'alpha_2': 'MV', 'alpha_3': 'MDV', 'country': 'Maldives'},
#     '457': {'alpha_2': 'MN', 'alpha_3': 'MNG', 'country': 'Mongolia'},
#     '459': {'alpha_2': 'NP', 'alpha_3': 'NPL', 'country': 'Nepal'},
#     '461': {'alpha_2': 'OM', 'alpha_3': 'OMN', 'country': 'Oman'},
#     '463': {'alpha_2': 'PK', 'alpha_3': 'PAK', 'country': 'Pakistan'},
#     '466': {'alpha_2': 'QA', 'alpha_3': 'QAT', 'country': 'Qatar'},
#     '468': {'alpha_2': 'SY', 'alpha_3': 'SYR', 'country': 'Syria'},
#     '470': {'alpha_2': 'AE', 'alpha_3': 'ARE', 'country': 'UAE'},
#     '472': {'alpha_2': 'TJ', 'alpha_3': 'TJK', 'country': 'Tajikistan'},
#     '473': {'alpha_2': 'YE', 'alpha_3': 'YEM', 'country': 'Yemen'},
#     '475': {'alpha_2': 'YE', 'alpha_3': 'YEM', 'country': 'Yemen'},
#     '477': {'alpha_2': 'HK', 'alpha_3': 'HKG', 'country': 'Hong Kong'},
#     '478': {'alpha_2': 'BA',
#             'alpha_3': 'BIH',
#             'country': 'Bosnia and Herzegovina'},
#     '501': {'alpha_2': 'AQ', 'alpha_3': 'ATA', 'country': 'Antarctica'},
#     '503': {'alpha_2': 'AU', 'alpha_3': 'AUS', 'country': 'Australia'},
#     '506': {'alpha_2': 'MM', 'alpha_3': 'MMR', 'country': 'Myanmar'},
#     '508': {'alpha_2': 'BN', 'alpha_3': 'BRN', 'country': 'Brunei'},
#     '510': {'alpha_2': 'FM', 'alpha_3': 'FSM', 'country': 'Micronesia'},
#     '511': {'alpha_2': 'PW', 'alpha_3': 'PLW', 'country': 'Palau'},
#     '512': {'alpha_2': 'NZ', 'alpha_3': 'NZL', 'country': 'New Zealand'},
#     '514': {'alpha_2': 'KH', 'alpha_3': 'KHM', 'country': 'Cambodia'},
#     '515': {'alpha_2': 'KH', 'alpha_3': 'KHM', 'country': 'Cambodia'},
#     '516': {'alpha_2': 'CX', 'alpha_3': 'CXR', 'country': 'Christmas Is'},
#     '518': {'alpha_2': 'CK', 'alpha_3': 'COK', 'country': 'Cook Is'},
#     '520': {'alpha_2': 'FJ', 'alpha_3': 'FJI', 'country': 'Fiji'},
#     '523': {'alpha_2': 'CC', 'alpha_3': 'CCK', 'country': 'Cocos Is'},
#     '525': {'alpha_2': 'ID', 'alpha_3': 'IDN', 'country': 'Indonesia'},
#     '529': {'alpha_2': 'KI', 'alpha_3': 'KIR', 'country': 'Kiribati'},
#     '531': {'alpha_2': 'LA', 'alpha_3': 'LAO', 'country': 'Laos'},
#     '533': {'alpha_2': 'MY', 'alpha_3': 'MYS', 'country': 'Malaysia'},
#     '536': {'alpha_2': 'MP', 'alpha_3': 'MNP', 'country': 'N Mariana Is'},
#     '538': {'alpha_2': 'MH', 'alpha_3': 'MHL', 'country': 'Marshall Is'},
#     '540': {'alpha_2': 'NC', 'alpha_3': 'NCL', 'country': 'New Caledonia'},
#     '542': {'alpha_2': 'NU', 'alpha_3': 'NIU', 'country': 'Niue'},
#     '544': {'alpha_2': 'NR', 'alpha_3': 'NRU', 'country': 'Nauru'},
#     '546': {'alpha_2': 'TF', 'alpha_3': 'ATF', 'country': 'French Polynesia'},
#     '548': {'alpha_2': 'PH', 'alpha_3': 'PHL', 'country': 'Philippines'},
#     '553': {'alpha_2': 'PG', 'alpha_3': 'PNG', 'country': 'Papua New Guinea'},
#     '555': {'alpha_2': 'PN', 'alpha_3': 'PCN', 'country': 'Pitcairn Is'},
#     '557': {'alpha_2': 'SB', 'alpha_3': 'SLB', 'country': 'Solomon Is'},
#     '559': {'alpha_2': 'AS', 'alpha_3': 'ASM', 'country': 'American Samoa'},
#     '561': {'alpha_2': 'WS', 'alpha_3': 'WSM', 'country': 'Samoa'},
#     '563': {'alpha_2': 'SG', 'alpha_3': 'SGP', 'country': 'Singapore'},
#     '564': {'alpha_2': 'SG', 'alpha_3': 'SGP', 'country': 'Singapore'},
#     '565': {'alpha_2': 'SG', 'alpha_3': 'SGP', 'country': 'Singapore'},
#     '566': {'alpha_2': 'SG', 'alpha_3': 'SGP', 'country': 'Singapore'},
#     '567': {'alpha_2': 'TH', 'alpha_3': 'THA', 'country': 'Thailand'},
#     '570': {'alpha_2': 'TO', 'alpha_3': 'TON', 'country': 'Tonga'},
#     '572': {'alpha_2': 'TV', 'alpha_3': 'TUV', 'country': 'Tuvalu'},
#     '574': {'alpha_2': 'VN', 'alpha_3': 'VNM', 'country': 'Vietnam'},
#     '576': {'alpha_2': 'VU', 'alpha_3': 'VUT', 'country': 'Vanuatu'},
#     '577': {'alpha_2': 'VU', 'alpha_3': 'VUT', 'country': 'Vanuatu'},
#     '578': {'alpha_2': 'WF', 'alpha_3': 'WLF', 'country': 'Wallis Futuna Is'},
#     '601': {'alpha_2': 'ZA', 'alpha_3': 'ZAF', 'country': 'South Africa'},
#     '603': {'alpha_2': 'AO', 'alpha_3': 'AGO', 'country': 'Angola'},
#     '605': {'alpha_2': 'DZ', 'alpha_3': 'DZA', 'country': 'Algeria'},
#     '607': {'alpha_2': 'XX', 'alpha_3': None, 'country': 'St Paul Amsterdam Is'},
#     '608': {'alpha_2': 'IO', 'alpha_3': 'IOT', 'country': 'Ascension Is'},
#     '609': {'alpha_2': 'BI', 'alpha_3': 'BDI', 'country': 'Burundi'},
#     '610': {'alpha_2': 'BJ', 'alpha_3': 'BEN', 'country': 'Benin'},
#     '611': {'alpha_2': 'BW', 'alpha_3': 'BWA', 'country': 'Botswana'},
#     '612': {'alpha_2': 'CF', 'alpha_3': 'CAF', 'country': 'Cen Afr Rep'},
#     '613': {'alpha_2': 'CM', 'alpha_3': 'CMR', 'country': 'Cameroon'},
#     '615': {'alpha_2': 'CG', 'alpha_3': 'COG', 'country': 'Congo'},
#     '616': {'alpha_2': 'KM', 'alpha_3': 'COM', 'country': 'Comoros'},
#     '617': {'alpha_2': 'CV', 'alpha_3': 'CPV', 'country': 'Cape Verde'},
#     '618': {'alpha_2': 'AQ', 'alpha_3': 'ATA', 'country': 'Antarctica'},
#     '619': {'alpha_2': 'CI', 'alpha_3': 'CIV', 'country': 'Ivory Coast'},
#     '620': {'alpha_2': 'KM', 'alpha_3': 'COM', 'country': 'Comoros'},
#     '621': {'alpha_2': 'DJ', 'alpha_3': 'DJI', 'country': 'Djibouti'},
#     '622': {'alpha_2': 'EG', 'alpha_3': 'EGY', 'country': 'Egypt'},
#     '624': {'alpha_2': 'ET', 'alpha_3': 'ETH', 'country': 'Ethiopia'},
#     '625': {'alpha_2': 'ER', 'alpha_3': 'ERI', 'country': 'Eritrea'},
#     '626': {'alpha_2': 'GA', 'alpha_3': 'GAB', 'country': 'Gabon'},
#     '627': {'alpha_2': 'GH', 'alpha_3': 'GHA', 'country': 'Ghana'},
#     '629': {'alpha_2': 'GM', 'alpha_3': 'GMB', 'country': 'Gambia'},
#     '630': {'alpha_2': 'GW', 'alpha_3': 'GNB', 'country': 'Guinea-Bissau'},
#     '631': {'alpha_2': 'GQ', 'alpha_3': 'GNQ', 'country': 'Equ. Guinea'},
#     '632': {'alpha_2': 'GN', 'alpha_3': 'GIN', 'country': 'Guinea'},
#     '633': {'alpha_2': 'BF', 'alpha_3': 'BFA', 'country': 'Burkina Faso'},
#     '634': {'alpha_2': 'KE', 'alpha_3': 'KEN', 'country': 'Kenya'},
#     '635': {'alpha_2': 'AQ', 'alpha_3': 'ATA', 'country': 'Antarctica'},
#     '636': {'alpha_2': 'LR', 'alpha_3': 'LBR', 'country': 'Liberia'},
#     '637': {'alpha_2': 'LR', 'alpha_3': 'LBR', 'country': 'Liberia'},
#     '642': {'alpha_2': 'LY', 'alpha_3': 'LBY', 'country': 'Libya'},
#     '644': {'alpha_2': 'LS', 'alpha_3': 'LSO', 'country': 'Lesotho'},
#     '645': {'alpha_2': 'MU', 'alpha_3': 'MUS', 'country': 'Mauritius'},
#     '647': {'alpha_2': 'MG', 'alpha_3': 'MDG', 'country': 'Madagascar'},
#     '649': {'alpha_2': 'ML', 'alpha_3': 'MLI', 'country': 'Mali'},
#     '650': {'alpha_2': 'MZ', 'alpha_3': 'MOZ', 'country': 'Mozambique'},
#     '654': {'alpha_2': 'MR', 'alpha_3': 'MRT', 'country': 'Mauritania'},
#     '655': {'alpha_2': 'MW', 'alpha_3': 'MWI', 'country': 'Malawi'},
#     '656': {'alpha_2': 'NE', 'alpha_3': 'NER', 'country': 'Niger'},
#     '657': {'alpha_2': 'NG', 'alpha_3': 'NGA', 'country': 'Nigeria'},
#     '659': {'alpha_2': 'NA', 'alpha_3': 'NAM', 'country': 'Namibia'},
#     '660': {'alpha_2': 'RE', 'alpha_3': 'REU', 'country': 'Reunion'},
#     '661': {'alpha_2': 'RW', 'alpha_3': 'RWA', 'country': 'Rwanda'},
#     '662': {'alpha_2': 'SD', 'alpha_3': 'SDN', 'country': 'Sudan'},
#     '663': {'alpha_2': 'SN', 'alpha_3': 'SEN', 'country': 'Senegal'},
#     '664': {'alpha_2': 'SC', 'alpha_3': 'SYC', 'country': 'Seychelles'},
#     '665': {'alpha_2': 'SH', 'alpha_3': 'SHN', 'country': 'St Helena'},
#     '666': {'alpha_2': 'SO', 'alpha_3': 'SOM', 'country': 'Somalia'},
#     '667': {'alpha_2': 'SL', 'alpha_3': 'SLE', 'country': 'Sierra Leone'},
#     '668': {'alpha_2': 'ST', 'alpha_3': 'STP', 'country': 'Sao Tome Principe'},
#     '669': {'alpha_2': 'SZ', 'alpha_3': 'SWZ', 'country': 'Swaziland'},
#     '670': {'alpha_2': 'TD', 'alpha_3': 'TCD', 'country': 'Chad'},
#     '671': {'alpha_2': 'TG', 'alpha_3': 'TGO', 'country': 'Togo'},
#     '672': {'alpha_2': 'TN', 'alpha_3': 'TUN', 'country': 'Tunisia'},
#     '674': {'alpha_2': 'TZ', 'alpha_3': 'TZA', 'country': 'Tanzania'},
#     '675': {'alpha_2': 'UG', 'alpha_3': 'UGA', 'country': 'Uganda'},
#     '676': {'alpha_2': 'CD', 'alpha_3': 'COD', 'country': 'DR Congo'},
#     '677': {'alpha_2': 'TZ', 'alpha_3': 'TZA', 'country': 'Tanzania'},
#     '678': {'alpha_2': 'ZM', 'alpha_3': 'ZMB', 'country': 'Zambia'},
#     '679': {'alpha_2': 'ZW', 'alpha_3': 'ZWE', 'country': 'Zimbabwe'},
#     '701': {'alpha_2': 'AR', 'alpha_3': 'ARG', 'country': 'Argentina'},
#     '710': {'alpha_2': 'BR', 'alpha_3': 'BRA', 'country': 'Brazil'},
#     '720': {'alpha_2': 'BO', 'alpha_3': 'BOL', 'country': 'Bolivia'},
#     '725': {'alpha_2': 'CL', 'alpha_3': 'CHL', 'country': 'Chile'},
#     '730': {'alpha_2': 'CO', 'alpha_3': 'COL', 'country': 'Colombia'},
#     '735': {'alpha_2': 'EC', 'alpha_3': 'ECU', 'country': 'Ecuador'},
#     '740': {'alpha_2': 'UK', 'alpha_3': None, 'country': 'UK'},
#     '745': {'alpha_2': 'GF', 'alpha_3': 'GUF', 'country': 'Guiana'},
#     '750': {'alpha_2': 'GY', 'alpha_3': 'GUY', 'country': 'Guyana'},
#     '755': {'alpha_2': 'PY', 'alpha_3': 'PRY', 'country': 'Paraguay'},
#     '760': {'alpha_2': 'PE', 'alpha_3': 'PER', 'country': 'Peru'},
#     '765': {'alpha_2': 'SR', 'alpha_3': 'SUR', 'country': 'Suriname'},
#     '770': {'alpha_2': 'UY', 'alpha_3': 'URY', 'country': 'Uruguay'},
#     '775': {'alpha_2': 'VE', 'alpha_3': 'VEN', 'country': 'Venezuela'}
# }

# commit_status = False
# mmsi_list = [x.mmsi for x in MMSI_Info.query.with_entities(MMSI_Info.mmsi).all()]
# for mmsi, dictionary in mmsi_dict.items():
#     if mmsi in mmsi_list:
#         continue
#     commit_status = True
#     dictionary['mmsi'] = mmsi
#     db.session.add(MMSI_Info(**dictionary))
# if commit_status:
#     db.session.commit()