# FROM tiangolo/uwsgi-nginx-flask:python3.7
FROM python:3.8
ENV TZ Asia/Taipei

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update
RUN apt-get install -y supervisor cron nano nodejs
RUN apt-get -y autoremove

RUN mkdir -p /var/log/supervisor

COPY supervisord.conf /etc/supervisor/supervisord.conf
COPY cron /etc/cron.d/cron
RUN chmod a+x /etc/cron.d/cron
RUN touch /var/log/cron.log
RUN crontab /etc/cron.d/cron

COPY first_run.sh /app/first_run.sh
COPY prestart.sh /app/prestart.sh
COPY requirements.txt /app/requirements.txt
RUN chmod a+x /app/first_run.sh
RUN chmod a+x /app/prestart.sh
RUN chmod a+x /app/requirements.txt
RUN /app/prestart.sh

CMD /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

WORKDIR /app